### ISSUE TITLE
Decide how the Gateway CRDs should be installed and what source we should use

### ISSUE THREAD

**Issue by ca-scribner** [canonical/istio-k8s-operator#5]
### Enhancement Proposal

As raised [in this PR comment](https://github.com/canonical/istio-k8s-operator/pull/4#discussion_r1688807720), we should choose what Gateway CRDs should be applied and how.  The

**Comment by ca-scribner** [comment]
@IbraAoad knew the difference between current and experimental CRDs, but I don't recall it.  I think in the `HTTPRoute` or one of those kinds of objects Istio relied on fields that were not in the full release yet.

**Comment by IbraAoad** [comment]
So the Istio getting started guide uses the experimental channel, yet I strongly believe that this is just because at the time of writing the guide service mesh capabilities in the gateway api wasn't graduated to GA yet in the standard channel (only graduated on the 9th of May)

Looking at the release notes in https://github.com/kubernetes-sigs/gateway-api/releases, the standard channel supports all gateway and ingress capabilities ( Gateways, HTTPRoutes, GRPCRoutes, ReferenceGrants), also when working on the ingress charm I've tested all functionalities using the standard channel and not the experimental one.

The experimental channel now include things such as (TCPRoute, TLSRoute, UDPRoute, Session Persistence + BackendLBPolicy, BackendTLSPolicy)

Using the standard channel will save us the hassle of dealing with breaking changes when introducing upgrade paths to our charms. By the time we implement features that require the experimental channel, it is likely to have already reached GA  and we'll have to introduce a painful (remove experimental/ add standard) upgrade scenario.
